### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by ElectricBlue1** [SnowShock35/JEIIntegration#1]
## JEIIntegration > 1.1.1.11

# Crash
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from JEI Integration (jeiintegration)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at com.snowshock35.jeiintegration.config.Config.loadConfig(Config.java:67)
	at com.snowshock35.jeiintegration.config.Config.<init>(Config.java:60)
	at com.snowshock35.jeiintegration.JEIIntegration.preInit(JEIIntegration.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:614)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:331)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:483)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 38 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_141, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 476418456 bytes (454 MB) / 1118306304 bytes (1066 MB) up to 1879048192 bytes (1792 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2423 132 mods loaded, 132 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2423-universal.jar) 
	UCH	forge{14.21.1.2423} [Minecraft Forge] (forge-1.12-14.21.1.2423-universal.jar) 
	UCH	appliedenergistics2-core{rv5-beta-2} [Applied Llamagistics Core] (minecraft.jar) 
	UCH	aroma1997core{1.3.0.0.b94} [Aroma1997Core] (Aroma1997Core-1.12-1.3.0.0.b94.jar) 
	UCH	securitycraft{v1.8.2.3-hotfix} [SecurityCraft] ([1.12] SecurityCraft v1.8.2.3-hotfix.jar) 
	UCH	actuallyadditions{1.12-r116} [Actually Additions] (ActuallyAdditions-1.12-r116.jar) 
	UCH	additionalbanners{1.5.38} [Additional Banners] (AdditionalBanners-1.12-1.5.38.jar) 
	UCH	akashictome{1.2-9} [Akashic Tome] (AkashicTome-1.2-9.jar) 
	UCH	applecore{2.2.2} [AppleCore] (AppleCore-mc1.12-2.2.2.jar) 
	UCH	jei{4.7.2.77} [Just Enough Items] (jei_1.12-4.7.2.77.jar) 
	UCH	appleskin{1.0.7} [AppleSkin] (AppleSkin-mc1.12-1.0.7.jar) 
	UCH	codechickenlib{3.1.1.288} [CodeChicken Lib] (CodeChickenLib-1.12-3.1.1.288-universal.jar) 
	UCH	redstoneflux{2.0.1} [Redstone Flux] (RedstoneFlux-1.12-2.0.1.2-universal.jar) 
	UCH	cofhcore{4.3.3} [CoFH Core] (CoFHCore-1.12-4.3.3.11-universal.jar) 
	UCH	cofhworld{1.0.0} [CoFH World] (CoFHWorld-1.12-1.0.0.6-universal.jar) 
	UCH	thermalfoundation{2.3.3} [Thermal Foundation] (ThermalFoundation-1.12-2.3.3.10-universal.jar) 
	UCH	thermalexpansion{5.3.3} [Thermal Expansion] (ThermalExpansion-1.12-5.3.3.15-universal.jar) 
	UCH	appliedenergistics2{rv5-beta-2} [Applied Llamagistics] (applied-llamagistics-1.12-rv5-beta-2.jar) 
	UCH	forgelin{1.5.1} [Shadowfacts' Forgelin] (Forgelin-1.5.1.jar) 
	UCH	mantle{1.12-1.3.0.15} [Mantle] (Mantle-1.12-1.3.0.15.jar) 
	UCH	chisel{MC1.12-0.0.13.14} [Chisel] (Chisel-MC1.12-0.0.13.14.jar) 
	UCH	tconstruct{1.12-2.7.1.9} [Tinkers' Construct] (TConstruct-1.12-2.7.1.9.jar) 
	UCH	thedragonlib{1.12-4.1.0} [TheDragonLib] (thedragonlib-1.12-4.1.0.jar) 
	UCH	armorplus{1.12-11.3.6.13-alpha} [ArmorPlus] (armorplus-1.12-11.3.6.13-alpha.jar) 
	UCH	aroma1997corehelper{1.3.0.0.b94} [Aroma1997Core|Helper] (Aroma1997Core-1.12-1.3.0.0.b94.jar) 
	UCH	aroma1997sdimension{1.3.0.0.b37} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar) 
	UCH	astralsorcery{1.6.1} [Astral Sorcery] (astralsorcery-1.12-1.6.1.jar) 
	UCH	morphtool{1.2-15} [Morph-o-Tool] (Morph-o-Tool-1.2-15.jar) 
	UCH	psi{r1.1-52} [Psi] (Psi-r1.1-52.jar) 
	UCH	quark{r1.2-103} [Quark] (Quark-r1.2-103.jar) 
	UCH	autoreglib{1.3-13} [AutoRegLib] (AutoRegLib-1.3-13.jar) 
	UCH	bedbugs{@VERSION@} [Bed Bugs] (BedBugs-1.12-1.0.1.jar) 
	UCH	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar) 
	UCH	bibliocraft{2.4.2} [BiblioCraft] (BiblioCraft[v2.4.2][MC1.12.0].jar) 
	UCH	biomesoplenty{7.0.0.2291} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2291-universal.jar) 
	UCH	bookshelf{2.0.415} [Bookshelf] (Bookshelf-1.12-2.0.0.415.jar) 
	UCH	brandonscore{2.3.0} [Brandon's Core] (BrandonsCore-1.12-2.3.0.120-universal.jar) 
	UCH	chameleon{1.12-4.1.3} [Chameleon] (Chameleon-1.12-4.1.3.jar) 
	UCH	chancecubes{1.12-3.0.1.199} [Chance Cubes] (ChanceCubes-1.12-3.0.1.199.jar) 
	UCH	chesttransporter{2.8.5} [Chest Transporter] (ChestTransporter-1.12-2.8.5.jar) 
	UCH	chiselsandbits{14.3} [Chisels & Bits] (chiselsandbits-14.3.jar) 
	UCH	cyclopscore{0.10.9} [Cyclops Core] (CyclopsCore-1.12-0.10.9.jar) 
	UCH	commoncapabilities{1.3.4} [CommonCapabilities] (CommonCapabilities-1.12-1.3.4.jar) 
	UCH	craftingtweaks{8.1.1} [Crafting Tweaks] (CraftingTweaks_1.12-8.1.1.jar) 
	UCH	crafttweaker{4.0.1} [CraftTweaker2] (CraftTweaker2-1.12-4.0.1.jar) 
	UCH	cucumber{1.0.0} [Cucumber] (cucumber[1.12]-1.0.0.jar) 
	UCH	cyclicmagic{1.6.1} [Cyclic] (Cyclic-1.12-1.6.1.jar) 
	UCH	darkutils{1.6.167} [Dark Utilities] (DarkUtils-1.12-1.6.167.jar) 
	UCH	dldungeonsjdg{1.9.3} [Doomlike Dungeons] (DoomlikeDungeons-1.9.3-MC1.12.jar) 
	UCH	draconicevolution{2.3.0} [Draconic Evolution] (Draconic-Evolution-1.12-2.3.0.255-universal.jar) 
	UCH	elevatorid{1.3.4} [Elevator Mod] (ElevatorMod-1.12-1.3.4.jar) 
	UCH	embers{0.221} [Embers] (embers-0.221.jar) 
	UCH	enderstorage{1.0} [EnderStorage] (EnderStorage-1.12-2.4.0.119-universal.jar) 
	UCH	enderutilities{0.7.2} [Ender Utilities] (enderutilities-1.12.0-0.7.2.jar) 
	UCH	everlastingabilities{1.3.1} [EverlastingAbilities] (EverlastingAbilities-1.12-1.3.1.jar) 
	UCH	exchangers{1.12-2.2} [Exchangers] (Exchangers-1.12-2.2.jar) 
	UCH	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.12-1.5.1.jar) 
	UCH	zerocore{1.12-0.1.0.9} [Zero CORE] (zerocore-1.12-0.1.0.9.jar) 
	UCH	bigreactors{1.12-0.4.5.34} [Extreme Reactors] (ExtremeReactors-1.12-0.4.5.34.jar) 
	UCH	flatcoloredblocks{mc1.12-6.3} [Flat Colored Blocks] (flatcoloredblocks-mc1.12-6.3.jar) 
	UCH	forestry{5.4.3.137} [Forestry] (forestry_1.12-5.4.3.137.jar) 
	UCH	mcmultipart{2.2.2} [MCMultiPart] (MCMultiPart-2.2.2.jar) 
	UCH	ftbl{0.0.0} [FTBLib] (FTBLib-4.0.5.jar) 
	UCH	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-4.0.3.jar) 
	UCH	funkylocomotion{1.0} [Funky Locomotion] (funky-locomotion-1.12-alpha-0.0.1.jar) 
	UCH	gravestone{1.8.4} [Gravestone Mod] (gravestone-1.8.4.jar) 
	UCH	storagedrawers{1.12-5.2.5} [Storage Drawers] (StorageDrawers-1.12-5.2.9.jar) 
	UCH	refinedstorage{1.5.13} [Refined Storage] (refinedstorage-1.5.13.jar) 
	UCH	growablecells{2.4.0} [Growable Cells] (Growable Cells-1.12-2.4.0.jar) 
	UCH	guideapi{1.12-2.1.3-55} [Guide-API] (Guide-API-1.12-2.1.3-55.jar) 
	UCH	harvest{1.12-1.2.4-16} [Harvest] (Harvest-1.12-1.2.4-16.jar) 
	UCH	tesla{1.0.60} [TESLA] (Tesla-1.12-1.0.60.jar) 
	UCH	theoneprobe{1.4.15} [The One Probe] (theoneprobe-1.12-1.4.15.jar) 
	UCH	immersiveengineering{0.12-69} [Immersive Engineering] (ImmersiveEngineering-0.12-69.jar) 
	UCH	improvedbackpacks{1.12-1.1.2.0} [Improved Backpacks] (ImprovedBackpacks-1.12-1.1.2.0.jar) 
	UCH	teslacorelib{1.12-1.0.5} [Tesla Core Lib] (tesla-core-lib-1.12-1.0.5.jar) 
	UCH	industrialforegoing{1.11.2-1.1} [Industrial Foregoing] (industrialforegoing-1.12-1.1-23.jar) 
	UCH	integrateddynamics{0.8.1} [Integrated Dynamics] (IntegratedDynamics-1.12-0.8.1.jar) 
	UCH	integrateddynamicscompat{1.0.0} [IntegratedDynamics-Compat] (IntegratedDynamics-1.12-0.8.1.jar) 
	UCH	integratedtunnels{1.2.5} [Integrated Tunnels] (IntegratedTunnels-1.12-1.2.5.jar) 
	UCH	inventorytweaks{1.63+beta.107.015dbec} [Inventory Tweaks] (InventoryTweaks-1.63+beta.107.jar) 
	UCH	ironchest{1.12-7.0.31.818} [Iron Chest] (ironchest-1.12-7.0.31.818.jar) 
	UCE	jeiintegration{1.1.1.11} [JEI Integration] (jeiintegration_1.12-1.1.1.11.jar) 
	UCH	jepb{1.2} [Just Enough Pattern Banners] (jepb-1.12-1.2.jar) 
	UCH	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	UCH	kleeslabs{5.3.2} [KleeSlabs] (KleeSlabs_1.12-5.3.2.jar) 
	UCH	login_shield{1.12-2-g338af14} [Login Shield] (Login_Shield-1.12-2-g338af14.jar) 
	UCH	lostcities{0.0.19beta} [The Lost Cities] (lostcities-1.12-0.0.19beta.jar) 
	UCH	lostsouls{0.0.2beta} [Lost Souls] (lostsouls-1.12-0.0.2beta.jar) 
	UCH	metamorph{1.1.3} [Metamorph] (metamorph-1.1.3-1.12.jar) 
	UCH	mob_grinding_utils{0.3.2} [mob_grinding_utils] (MobGrindingUtils-0.3.2.jar) 
	UCH	morpheus{1.12-3.3.2} [Morpheus] (Morpheus-1.12-3.3.2.jar) 
	UCH	mputils{1.4.1} [MPUtils] (MPUtils-1.12-1.4.1.jar) 
	UCH	mpbasic{1.3.0} [ModPack Basic Tools] (mpbasic-1.12-1.3.0.jar) 
	UCH	mysticalagriculture{1.6.2} [Mystical Agriculture] (mysticalagriculture[1.12]-1.6.2.jar) 
	UCH	natura{1.12-4.3.0.10} [Natura] (Natura-1.12-4.3.0.10.jar) 
	UCH	netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.12-5.3.1.jar) 
	UCH	notenoughwands{1.5.9} [Not Enough Wands] (notenoughwands-1.12-1.5.9.jar) 
	UCH	oreexcavation{1.4.100} [OreExcavation] (OreExcavation-1.4.100.jar) 
	UCH	plustic{6.0.0.3} [PlusTiC] (plustic-6.0.0.3.jar) 
	UCH	reborncore{3.2.5.88} [Reborn Core] (RebornCore-1.12-3.2.5.88-universal.jar) 
	UCH	quantumstorage{4.3.5} [QuantumStorage] (QuantumStorage-1.12-4.3.5.jar) 
	UCH	quickleafdecay{1.2.3} [Quick Leaf Decay] (QuickLeafDecay-MC1.12-1.2.3.jar) 
	UCH	randomthings{4.0.3} [Random Things] (RandomThings-MC1.12-4.0.3.jar) 
	UCH	rangedpumps{0.5} [Ranged Pumps] (rangedpumps-0.5.jar) 
	UCH	redstonearsenal{2.3.3} [Redstone Arsenal] (RedstoneArsenal-1.12-2.3.3.11-universal.jar) 
	UCH	refinedstorageaddons{0.1.1} [Refined Storage Addons] (refinedstorageaddons-0.1.1.jar) 
	UCH	rflux{0.1.1} [RF Lux] (rflux-1.12-0.1.1.jar) 
	UCH	rftools{6.12} [RFTools] (rftools-1.12-6.12.jar) 
	UCH	rftoolscontrol{1.6.8} [RFTools Control] (rftoolsctrl-1.12-1.6.8.jar) 
	UCH	rftoolsdim{5.04} [RFTools Dimensions] (rftoolsdim-1.12-5.04.jar) 
	UCH	roots{0.025} [Roots 2] (roots-2-0.025.jar) 
	UCH	rustic{0.3.12} [Rustic] (rustic-0.3.12.jar) 
	UCH	shetiphiancore{3.5.0.2} [ShetiPhian-Core] (shetiphiancore-1.12.0-3.5.0.2.jar) 
	UCH	simplyconveyors{3.0.6} [Simply Conveyors & More] (SimplyConveyors-4.0.4.jar) 
	UCH	soulshardstow{1.12-2.7.3-52} [Soul Shards - The Old Ways] (SoulShards-TOW-1.12-2.7.3-52.jar) 
	UCH	storagedrawersextra{@VERSION@} [Storage Drawers Extras] (StorageDrawersExtras-1.12-3.1.0.jar) 
	UCH	tails{1.12-1.10.0} [Tails] (Tails-1.12-1.10.0.jar) 
	UCH	techreborn{2.6.9.165} [Tech Reborn] (TechReborn-1.12-2.6.9.165-universal.jar) 
	UCH	terraqueous{1.4.0.3} [Terraqueous] (terraqueous-1.12.0-1.4.0.3.jar) 
	UCH	thermalcultivation{0.1.0} [Thermal Cultivation] (ThermalCultivation-1.12-0.1.0.5-universal.jar) 
	UCH	thermaldynamics{2.3.3} [Thermal Dynamics] (ThermalDynamics-1.12-2.3.3.10-universal.jar) 
	UCH	topaddons{1.12-0.15.0} [TOP Addons] (topaddons-1.12-0.15.0.jar) 
	UCH	usefulnullifiers{1.4.1} [Useful Nullifiers] (usefulnullifiers-1.4.1.jar) 
	UCH	waterpower{@MODVERSION@} [WaterPower] (WaterPower-1.12-0.5.5.jar) 
	UCH	waterstrainer{3.1.1} [Water Strainer] (WaterStrainer-1.12-3.1.1.jar) 
	UCH	waystones{4.0.5} [Waystones] (Waystones_1.12-4.0.5.jar) 
	UCH	xnet{1.3.5} [XNet] (xnet-1.12-1.3.5.jar) 
	UCH	xtones{1.12-1.0.4-7} [Xtones] (Xtones-1.12-1.0.4-7.jar) 
	UCH	teslacoreregistries{1.12-1.0.5} [Tesla Core Registries] (tesla-core-lib-1.12-1.0.5.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (ResourceLoader-MC1.12-1.5.2.jar)
  lumien.resourceloader.asm.ClassTransformer
AstralCore (astralsorcery-1.12-1.6.1.jar)
  
ForgelinPlugin (Forgelin-1.5.1.jar)
  
LoadingPlugin (Quark-r1.2-103.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.12-4.0.3.jar)
  lumien.randomthings.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.12-0.2.0.3.jar)
  team.chisel.ctm.client.asm.CTMTransformer
CoreMod (Aroma1997Core-1.12-1.3.0.0.b94.jar)
  
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.0.2.jar)
  shetiphian.asm.ClassTransformer
CoreModLoader (applied-llamagistics-1.12-rv5-beta-2.jar)
  appeng.coremod.transformer.ASMIntegration
Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.107.jar)
  invtweaks.forge.asm.ContainerTransformer
BlurPlugin (Blur-1.0.3-13.jar)
  com.tterrag.blur.BlurTransformer
IELoadingPlugin (ImmersiveEngineering-0.12-69.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
AppleCore (AppleCore-mc1.12-2.2.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
	AE2 Version: beta rv5-beta-2 for Forge 14.21.1.2387
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.2.5.88
		Runtime Debofucsation 1
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by SnowShock35** [comment]
Fixed via 44a229a0649d970f009c2504336712a411a052c8
