### ISSUE TITLE
Declare your mod is client Side to forge

### ISSUE THREAD

**Issue by tyler489** [SnowShock35/JEIIntegration#3]
im getting an exception on my server because forge doesn't recognize that your mod is clientside only see #2

**Comment by SnowShock35** [comment]
@tyler489 Did u update to 1.2.0 yet? Pretty sure I fixed this.

**Comment by tyler489** [comment]
jeiintegration_1.11.2-1.1.0.10 will reopen if still an issue after next weeks update

**Comment by SnowShock35** [comment]
1.1.0 wont work on server. Please update to 1.2.0.
